ConvertFrom-StringData -StringData @'
	FirstDeployment           = Erste Erfahrungen mit Bereitstellung
	FirstDeploymentPopup      = Öffnen Sie die Hauptschnittstelle
	FirstExpFinishOnDemand    = Erlaube die erste Vorerfahrung, wie geplant
	SettingLangAndKeyboard    = Systemsprache und Tastatur einstellen
	SettingUTF8               = Beta Version: Unicode UTF-8 verwenden Globale Sprachunterstützung verfügbar
	SettingUTF8Tips           = Es kann nach der Verwendung zu neuen Problemen führen.
	SettingLocale             = Systemgebietsschema festlegen
	SettingLocaleTips         = Gültig, wenn kein Bereitstellungszonen-Tag vorhanden ist.
	PreAppxCleanup            = Appx-Bereinigungswartungsaufgaben
	CleanupOndemandLP         = Verhindern Sie die Bereinigung nicht verwendeter Sprachpakete
	CleanupUnusedLP           = Verhindern Sie die Bereinigung nicht verwendeter Feature-on-Demand-Sprachpakete
	Restricted                = Powershell Ausführungsstrategie fortsetzen: Eingeschränkt
	DiskSearch                = Vollständiger Festplattensuchplan: \
	DiskSearchFind            = Gefunden, läuft: {0}
	DeployCleanup             = Deploy Verzeichnis aufräumen
	DeployTask                = Bereitstellungsaufgaben: \
	Reboot                    = Starten Sie den Computer neu
	NetworkLocationWizard     = Netzwerkstandort Assistent
	LangMul                   = Mehrsprachig
	LangSingle                = Einsprachig
	RandomlyWaitSel           = Warten Sie auf die zufällig ausgewählte Sprache
	RandomlySelResults        = Ergebnisse nach dem Zufallsprinzip auswählen
	LanguageInstalled         = Auf dem System ist ein Sprachpaket installiert.
	SetLang                   = Vom System bevorzugte Sprache einstellen: \
	SetTimezone               = Zeitzone einstellen: \
	KeyboardSequence          = Tastatursequenz: \
	Wubi                      = Wubi
	Pinyi                     = Pinyin
	VolumeLabel               = Volume Label des Systemlaufwerks festlegen: {0}
	SelectVolumename          = Wählen Sie den Namen des Volume Labels "Systemfestplatte"
	Exclude                   = Defender ausschließen
	FixMainFolder             = {0} Verzeichnissymbol reparieren
	Authority                 = verstecktes Verzeichnis oder Datei
	NextDelete                = Nach dem nächsten Login die Bonuslösung bereinigen
'@