ConvertFrom-StringData -StringData @'
	Mainname                  = Deployment Engine: Yi's Suite
	MainHisName               = Bundled Solutions
	Location                  = Open location
	About                     = About
	Reset                     = Reset
	AddTo                     = Add
	Instl                     = Installation
	ItInstalled               = Installed
	Close                     = Close
	Auto                      = Automatic
	Disable                   = Disabled
	Enabled                   = Enabled
	Setting                   = Set up
	Restore                   = Restore
	Clean                     = Clean up
	Operable                  = Operable
	Inoperable                = Inoperable
	Optimize                  = Optimization
	Hide                      = Hide
	Show                      = Show
	Delete                    = Delete
	Done                      = Complete
	OK                        = OK
	Cancel                    = Cancel
	AllSel                    = Select all
	AllClear                  = Clear all
	Refresh                   = Refresh
	RefreshModules            = Hot refresh all modules
	ForceUpdate               = Forcibly chec
	Necessary                 = Necessary software
	MostUsedSoftware          = Commonly used software
	System                    = System
	Service                   = Service
	TaskBar                   = All icons in the taskbar
	DeskIcon                  = Desktop icon
	InstallFonts              = Install fonts
	SettingTo                 = Set to {0}
	SwitchLanguage            = Switch language
	PleaseChoose              = Please select
	FailedCreateFolder        = Failed to create directory: \
	ToMsg                     = \n   Automatically return to the main menu after {0} seconds.
	ToQuit                    = \n   Exit the main menu in {0} seconds.
	Restart                   = Restart to take effect
	AdvOption                 = Optional function

	StartDown                 = Start download
	ConnectTo                 = Connect to
	FileName                  = File name
	SaveTo                    = Save to
	NotAvailable              = Status: Unavailable
	ExistingPacker            = Existing installation package
	ExistingInstlPacker       = Existing compressed package
	Unpacking                 = Unpacking
	QucikRun                  = Quick run: \
	WaitDone                  = Waiting for completion: \
	Parameter                 = Parameters: \
	ErrorDown                 = An error occurred during download
	UserCancel                = The user has cancelled the operation.

	VerifyNameTips            = Only the combination of English letters and numbers is allowed, and other characters are not allowed: spaces, the length cannot be greater than 260 characters, \\ / : * ? & @ ! "" < > |
	FolderLabel               = Custom directory prefix
	NoSetFolderLabel          = The custom directory prefix is not set
	ISO9660TipsErrorSpace     = Cannot contain: leading and trailing spaces
	ISO9660TipsErrorOther     = Cannot contain: \\ / : * ? & @ ! "" < > |
	ISOLengthError            = The label length cannot be greater than {0} characters
'@